ALTER TABLE events ADD COLUMN output_achievement INTEGER NOT NULL DEFAULT 0;
ALTER TABLE events ADD COLUMN outcome_achievement INTEGER NOT NULL DEFAULT 0;
ALTER TABLE events ADD COLUMN impact_achievement INTEGER NOT NULL DEFAULT 0;
ALTER TABLE events ADD COLUMN swot_strengths TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN swot_weaknesses TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN swot_opportunities TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN swot_threats TEXT NOT NULL DEFAULT '';
